### ISSUE TITLE
CSS issue in locator in mobile view

### ISSUE THREAD

**Issue by Thanusha12** [hlxsites/sazerac-99brandparty#114]
1.In Mobile view, the fields in locator are placed too close to each other and needs to be stacked vertically - 

https://main--sazerac-99brandparty--hlxsites.hlx.live/where-to-buy
![image](https://github.com/hlxsites/sazerac-99brandparty/assets/122380883/7def1545-d151-4d5c-aa1c-272c639a94c0)

 
Original site - 
![image](https://github.com/hlxsites/sazerac-99brandparty/assets/122380883/a3ba57bb-bd3a-4c8a-a947-349a60a1ebf8)

**Comment by RemoLiechti** [comment]
I have added the wrapping into a columns, but I centered it as the results are centered too. Looks better visually I believe.
![image](https://github.com/hlxsites/sazerac-99brandparty/assets/141611642/3862689c-4806-4f11-b28c-94adece5efeb)
