### ISSUE TITLE
CSS issue in Contact us Page(Mobile view)

### ISSUE THREAD

**Issue by Thanusha12** [hlxsites/sazerac-99brandparty#117]
1.The content in Contact us page requires margin on both sides in mobile view iphone 12 pro 390x844.
https://main--sazerac-99brandparty--hlxsites.hlx.live/say-hello

![image](https://github.com/hlxsites/sazerac-99brandparty/assets/122380883/aa4a77f3-9be5-41f3-862e-40e73307d070)

original site - 

![image](https://github.com/hlxsites/sazerac-99brandparty/assets/122380883/23bf3c8d-9d1f-4fd9-8780-242d726e1d48)

**Comment by RemoLiechti** [comment]
done.
I also shrinked the note text area a little in height, so that the send button is not covered by the recaptcha:

![image](https://github.com/hlxsites/sazerac-99brandparty/assets/141611642/f5c1399b-a88f-4e69-9f18-68e3b8408f19)
