### ISSUE TITLE
Alignment issues 

### ISSUE THREAD

**Issue by Thanusha12** [hlxsites/sazerac-99brandparty#97]
1. The text in Age gate is not aligned to center
![image](https://github.com/hlxsites/sazerac-99brandparty/assets/122380883/206da552-7041-4ff9-8121-b98333c1ee84)

2. The "Previous" button in all the product pages has lot of space on the right. 

![image](https://github.com/hlxsites/sazerac-99brandparty/assets/122380883/cb5978da-116d-4925-9817-97b1a8f18d2a)

**Comment by RemoLiechti** [comment]
Hi @Thanusha12 , what screen resolution / window size are you using? That would help to narrow it down, thanks.

**Comment by Thanusha12** [comment]
Hey @RemoLiechti my screen size is quite small its 1366x768 but I tested this again in 1920x1080 and in mobile view and the age gate looks good.

Is the button style changed? because I see a small arrow in the button in the original site -
![image](https://github.com/hlxsites/sazerac-99brandparty/assets/122380883/133c6475-89e2-44b7-a30a-e7eb866db80c)

**Comment by RemoLiechti** [comment]
agegate: ok then I will not apply any changes there.
buttons: yes, I skipped the small arrow as no other buttons on the site do have that. Do you believe we shall add it?

**Comment by RemoLiechti** [comment]
alignment is fixed, let me know about the small arrow icon.
as for the alignment, do you think we should keep the longer divider between buttons, or make it smaller? 

Original:
<img width="1112" alt="image" src="https://github.com/hlxsites/sazerac-99brandparty/assets/141611642/bb5db1d9-f938-427d-8e38-3f6fe339fb10">


ours:
![image](https://github.com/hlxsites/sazerac-99brandparty/assets/141611642/4e81c765-5257-46d7-afee-c6fbc087ff42)

**Comment by Thanusha12** [comment]
1. I also feel the arrows are not required.

2. we can keep the divider small to match the original site. 

3. The buttons looks tight in mobile view(390x844 iphone 12 pro) a little margin/padding I guess would fix it.
![image](https://github.com/hlxsites/sazerac-99brandparty/assets/122380883/e47be82b-88b8-4fd9-b468-44c9c42dd8b0)

**Comment by RemoLiechti** [comment]
1. agreed
2. done, see below.
3. done, see below.

I have no optimized this for quite some different widths of the screen. so now we should have a good way for any screensize.

![image](https://github.com/hlxsites/sazerac-99brandparty/assets/141611642/49a6dd48-a926-46c5-bf63-061ef98bc24f)
![image](https://github.com/hlxsites/sazerac-99brandparty/assets/141611642/8252c7f9-6122-473a-9286-2fbfb8e67333)
![image](https://github.com/hlxsites/sazerac-99brandparty/assets/141611642/f0b8dcf1-fcbf-4c3e-9954-f28b7d643442)
![image](https://github.com/hlxsites/sazerac-99brandparty/assets/141611642/5d01d20f-870c-4ba3-b881-809f012efaa5)
![image](https://github.com/hlxsites/sazerac-99brandparty/assets/141611642/9f35e1c0-bfb9-4715-84be-1196f1c6c136)
![image](https://github.com/hlxsites/sazerac-99brandparty/assets/141611642/30a2c9ec-b551-47ae-9603-c76f6b264a1a)
![image](https://github.com/hlxsites/sazerac-99brandparty/assets/141611642/9ded804b-a033-497f-9e11-07d3e78827cc)

![image](https://github.com/hlxsites/sazerac-99brandparty/assets/141611642/e4210154-e33f-4cb4-bd85-5a661b0515af)
